print('/informe seus dados pesssoais.')
nome = str(input('Nome: '))
sobre_nome = str(input('Sobre nome: '))
idade = int(input('Idade: '))
ano_Nascimento = int(input('Data de nasimento: '))
altura = float(input('Altura: '))
maior_De_Idade = idade >= 18

print('Nome:', nome)
print('Sobre nome:', sobre_nome)
print('Idade:', idade)
print('Ano de nascimento:', ano_Nascimento)
print('É maior de Idade?', maior_De_Idade)
print('Altura em metros:', altura)
print('=*' * 30)
print(f'{nome} {sobre_nome}, você tem {idade} anos, nasceu em {ano_Nascimento} é maior de idade? {maior_De_Idade}, sua altura é {altura}.')
